Repository wecode-bootcamp-korea/30-1st-chadamhwa-frontend, pull requests merged in 2022-03, with the labels that each got.

#6 [30기 박철진] feature/Router 라우트 경로 수정
  src/Router.js
Labels: Status: Accepted

#7 [30기 박별] nav 분리 완료
  public/images/image.png
  public/images/logo.jpeg
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 수정 요청

#8 [30기 박별] Fix : subnav 분리완료
  src/components/Subnav/Subnav.js
  src/components/Subnav/Subnav.scss
Labels: Status: 수정 요청

#12 Feature/event
  public/images/banner2.png
  public/images/banner3.png
  public/images/event0.png
  public/images/event1.png
  public/images/event2.png
  public/images/event3.png
  public/images/event4.png
  src/Router.js
  src/pages/Event/Event.js
  src/pages/Event/Event.scss
Labels: Status: 추가 기능 구현중

#5 [30기 신윤지] feature/Detail
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/Intro.js
  src/pages/Detail/Rate.js
  src/pages/Detail/Review.js
  src/pages/Detail/Review.scss
  src/pages/Detail/ReviewList.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#4 [30기 박철진] feature/products
  .vscode/settings.json
  public/data/data.json
  public/images/alisher-sharip-mumpl9-D7Uc-unsplash.jpg
  public/images/products-banner.png
  src/Router.js
  src/pages/Products/Product.js
  src/pages/Products/Product.scss
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
Labels: Status: 수정 요청, Status: 추가 기능 구현중
